<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Authors>Jakub Maly;Stef Heyenrath</Authors>
    <TargetFrameworks>net472;net48;net481;net8.0;net10.0</TargetFrameworks>
    <AssemblyName>ParserTest</AssemblyName>
    <OutputType>Exe</OutputType>
    <PackageId>ParserTest</PackageId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CommandLineArgumentsParser\CommandLineArgumentsParser.csproj" />
  </ItemGroup>

</Project>