os: Visual Studio 2022

version: 4.0.0.{build}

configuration:
- Debug
- Release

platform: Any CPU

init:
- ps: $Env:LABEL = "CI" + $Env:APPVEYOR_BUILD_NUMBER.PadLeft(5, "0")

build_script:
 - cmd: dotnet --info

 - cmd: dotnet restore src\CommandLineArgumentsParser\CommandLineArgumentsParser.csproj
 - cmd: dotnet build src\CommandLineArgumentsParser\CommandLineArgumentsParser.csproj --configuration %CONFIGURATION% --framework netstandard2.0
 - cmd: dotnet build src\CommandLineArgumentsParser\CommandLineArgumentsParser.csproj --configuration %CONFIGURATION% --framework netstandard2.1

 - cmd: dotnet restore src\ParserTest\ParserTest.csproj
 - cmd: dotnet build src\ParserTest\ParserTest.csproj --configuration %CONFIGURATION% --framework net472
 - cmd: dotnet build src\ParserTest\ParserTest.csproj --configuration %CONFIGURATION% --framework net48
 - cmd: dotnet build src\ParserTest\ParserTest.csproj --configuration %CONFIGURATION% --framework net481
 - cmd: dotnet build src\ParserTest\ParserTest.csproj --configuration %CONFIGURATION% --framework net8.0
 - cmd: dotnet build src\ParserTest\ParserTest.csproj --configuration %CONFIGURATION% --framework net10.0

 - cmd: dotnet restore src\Tests\Tests.csproj
 - cmd: dotnet build src\Tests\Tests.csproj --configuration %CONFIGURATION% --framework net10.0

test_script:
 - cmd: dotnet test src\Tests\Tests.csproj --configuration %CONFIGURATION% --framework net10.0

cache:
- '%USERPROFILE%\.nuget\packages'